[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#libc = "0.2.121"
#rand = "0.8.5"
#math = "0.10.0"
plotters = "0.3.1"